---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lstocks3/luisgtechgroup.com/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
